site_name: Dynreact 

site_url: ""
use_directory_urls: false
docs_dir: docsSrc
site_dir: docs

theme:
  name: "readthedocs"
  color_mode: light
  highlightjs: true

nav:
  - Overview: index.md
  - DynReActBase: ./DynReActBase/index.html
  - ShortTermPlanning: ./ShortTermPlanning/index.html
  - Service: ./service/index.html
