services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Debian Base image
        VARIANT: "debian"
        # Update 'PYTHON_VERSION' to pick a Python version: 3, 3.12, 3.11, 3.10, 3.9, 3.8
        PYTHON_VERSION: "3.12"
        # Node 20
        NODE_VERSION: "lts/iron"

    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace:cached

    networks:
      - kafka-net

    depends_on:
      - kafka
      - kafkaUi
      
    # Overrides default command so things don't shut down after the process ends.
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity 

    # Uncomment the next line to use a non-root user for all processes.
    user: vscode

  kafkaUi:
    image: "provectuslabs/kafka-ui:latest"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    volumes:
      - ./kafka/config.yml:/etc/kafkaui/dynamic_config.yaml

    ports:
      - "8080:8080" # This is needed for forwardPorts to work

    networks:
      - kafka-net
    depends_on:
      - kafka

  zookeeper:
      image: bitnami/zookeeper:latest
      environment:
        ALLOW_ANONYMOUS_LOGIN: yes
      networks:
        - kafka-net

  kafka:
    image: bitnami/kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: yes
      JMX_PORT: 9999
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: kafka

    ports:
      - "9092:9092"
      - "9999:9999"

    depends_on:
      - zookeeper
    networks:
      - kafka-net

networks:
  kafka-net:
