site_name: Dynreact ShortTermPlanning

site_url: ""
use_directory_urls: false


docs_dir: docs
extra:
  source_dir: dynreact

theme:
  name: "readthedocs"
  color_mode: light
  highlightjs: true


plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          members_order: source
          docstring_section_style: table
          docstring_style: google
          docstring_options:
            ignore_init_summary: false
            trim_doctest_flags: false

nav:
  - General: index.md
  - Agent: agent.md
  - Material: material.md
  - Equipment: equipment.md
  - Common: common.md
  - Log: log.md
  - Functions: functions.md
  - Clean_kafka: cleankafka.md
  - ShortTermPlanning: shorttermplanning.md
