site_name: Dynreact Base

site_url: ""
use_directory_urls: false

theme:
  name: "readthedocs"
  color_mode: light
  highlightjs: true


plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          members_order: source
          show_source: true
          docstring_section_style: table
          docstring_style: google
          docstring_options:
            ignore_init_summary: false
            trim_doctest_flags: false

nav:
  - General: index.md
  - Cost provider: cost_provider.md
  - Lots optimizer: lots_optimizer.md
  - Model: model.md
  - Snapshot provider: snapshot_provider.md
  - Long term planning: longtermplanning.md
