site_name: Dynreact Base

site_url: ""
use_directory_urls: false

theme:
  name: "readthedocs"
  color_mode: light
  highlightjs: true


plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          members_order: source
          show_source: true
          docstring_section_style: table
          docstring_style: google
          docstring_options:
            ignore_init_summary: false
            trim_doctest_flags: false

nav:
  - Back: ../index.html
  - General: index.md
  - Model: model.md
  - Snapshot provider: snapshot_provider.md
  - Snapshot importer: snapshot_importer.md
  - Shifts provider: shifts_provider.md
  - Production history reader: prod_history_reader.md
  - Lot sink: lot_sink.md
  - Cost provider: cost_provider.md
  - Long term planning: longtermplanning.md
  - Lots optimizer: lots_optimizer.md
  - Plant performance model: plant_performance_model.md
